---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LaGeogeoTeam.
--- DateTime: 19/09/2025 16:24
---

-- camera.lua (zoom + clamp + resize + pixel-perfect)
local Camera = {}
Camera.__index = Camera

function Camera.new()
    local self = setmetatable({}, Camera)
    self.x, self.y = 0, 0
    self.scale = 1      -- 1 = pas de zoom ; >1 = zoom avant
    self.minScale = 1
    self.maxScale = 3
    self.zoomStep = 0.25
    self.lerp = 10
    self.worldW = love.graphics.getWidth()
    self.worldH = love.graphics.getHeight()
    self.w = love.graphics.getWidth()   -- largeur VISIBLE en unités monde (maj via updateViewport)
    self.h = love.graphics.getHeight()
    return self
end

function Camera:updateViewport()
    -- zone visible en unités "monde" après zoom
    self.w = love.graphics.getWidth()  / self.scale
    self.h = love.graphics.getHeight() / self.scale
end

function Camera:setWorld(worldW, worldH)
    self.worldW, self.worldH = worldW, worldH
    self:updateViewport()
end

function Camera:setScale(s)
    self.scale = math.max(self.minScale, math.min(self.maxScale, s))
    self:updateViewport()
end

function Camera:zoomIn()  self:setScale(self.scale + self.zoomStep) end
function Camera:zoomOut() self:setScale(self.scale - self.zoomStep) end
function Camera:resetZoom() self:setScale(1) end

local function clamp(v, a, b)
    if a > b then return (a + b) * 0.5 end
    if v < a then return a end
    if v > b then return b end
    return v
end

function Camera:follow(tx, ty, dt)
    -- centre recherché (tx/ty = pos joueur en monde)
    local targetX = tx - self.w * 0.5
    local targetY = ty - self.h * 0.5

    -- lissage
    local k = math.min(1, self.lerp * (dt or 0))
    self.x = self.x + (targetX - self.x) * k
    self.y = self.y + (targetY - self.y) * k

    -- clamp aux bords (si monde plus petit que vue, max = 0 => x/y = 0)
    local maxX = math.max(0, self.worldW - self.w)
    local maxY = math.max(0, self.worldH - self.h)
    self.x = clamp(self.x, 0, maxX)
    self.y = clamp(self.y, 0, maxY)
end

function Camera:attach()
    love.graphics.push()
    -- pixel art net même en zoom : voir setDefaultFilter côté main.lua
    love.graphics.scale(self.scale, self.scale)
    love.graphics.translate(-math.floor(self.x), -math.floor(self.y))
end

function Camera:detach()
    love.graphics.pop()
end

-- à appeler depuis love.resize(w,h)
function Camera:resize()
    self:updateViewport()
end

return Camera