---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LaGeogeoTeam.
--- DateTime: 25/09/2025 21:54
---
-- maps/dungeon.lua
local Loader = require "tiled_loader"
local dungeon = {}

local map = Loader.load("assets.maps.dungeon")

function dungeon.draw(camera)
    local viewW = love.graphics.getWidth()  / camera.scale
    local viewH = love.graphics.getHeight() / camera.scale
    map:drawVisible(camera.x, camera.y, viewW, viewH)
end

function dungeon.getWorldSize()
    return map:getWorldSize()
end

return dungeon
