---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LaGeogeoTeam.
--- DateTime: 19/09/2025 17:33
---
-- thirdmap.lua
local thirdmap = {}

-- dimensions propres à la map
thirdmap.width  = 64
thirdmap.height = 48

-- Génération d'une pièce avec bordures solides
local function generateRoom(w, h, wallId, floorId)
    local t = {}
    local c = 1
    for y = 1, h do
        for x = 1, w do
            local isBorder = (x == 1 or y == 1 or x == w or y == h)
            t[c] = isBorder and wallId or floorId
            c = c + 1
        end
    end
    return t
end

-- Remplis la grille
thirdmap.grid = generateRoom(thirdmap.width, thirdmap.height, 3, 1)

-- Décor (props) en plus
local arbre = love.graphics.newImage("assets/images/arbre.png")
local house = love.graphics.newImage("assets/images/house.png")
thirdmap.props = {
    {img = arbre, x = 300, y = 300},
    {img = arbre, x = 900, y = 240},
    {img = house, x = 1400, y = 900},
}

function thirdmap.draw()
    local cpt = 1
    for y = 1, thirdmap.height do
        for x = 1, thirdmap.width do
            local tileId = thirdmap.grid[cpt]
            love.graphics.draw(get_tile_by_id(tileId), (x-1)*tileSize, (y-1)*tileSize)
            cpt = cpt + 1
        end
    end
    for _, p in ipairs(thirdmap.props) do
        love.graphics.draw(p.img, p.x, p.y)
    end
end

function thirdmap.getWorldSize()
    return thirdmap.width * tileSize, thirdmap.height * tileSize
end

return thirdmap
